include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_MOOD_GATE_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_MOOD_GATE_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_MOOD_GATE_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_MOOD_GATE)

MAINSRC = mood_gate_main.c mood_gate.c mood_gate_model_params.c mood_gate_platform.c

include $(APPDIR)/Application.mk
